sudo: required
services:
    - docker
before_install:
    - docker build -t poulamisahadocker/docker-react -f DockerFile.dev .

script:
    - docker run poulamisahadocker/docker-react npm run test -- --coverage