sudo: required
services:
  - docker
before_install:
  - docker build -t poulamisahadocker/docker-react -f DockerFile.dev .

script:
  - docker run -e CI=true poulamisahadocker/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-580133431409"
  bucket_path: "docker-react"
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: $AWS_SECRET_KEY
